### ISSUE TITLE
Incorrect key usage (ie, lacks keyEncipherment or serverAuth)

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#28] opened 2015-05-15 18:38 UTC
From [this comment](https://github.com/lgarron/badssl.com/issues/1#issuecomment-98006735) by marumari@.

**Comment by marumari** [comment] 2015-11-30 23:59
Looks like this is a duplicate of #118.

**Closed by marumari** 2015-11-30 23:59 UTC
Labels: subdomain
